# Custom Callouts

This page demonstrates the use of the [`quarto-custom-callout`](https://quarto.thecoatlessprofessor.com/custom-callout/) extension to provide bespoke callout blocks.

- [`quarto-custom-callout` repository](https://github.com/coatless-quarto/custom-callout)
- [`quarto-custom-callout` examples and documentation](https://quarto.thecoatlessprofessor.com/custom-callout/)

## Introduction

Quarto provides a number of built-in callout blocks, including:

::: { .callout-caution }
The caution callout

```markdown
::: { .callout-caution }
The caution callout
:::
```
:::

::: { .callout-important }
The important callout

```markdown
::: { .callout-info }
The important callout
:::
```
:::

::: { .callout-tip }
The tip callout

```markdown
::: { .callout-tip }
The tip callout
:::
```
:::

but these do not cover all the cases we might want to use callouts for. It is possible to change the titles of these callouts, such as:

::: { .callout-tip title="Custom title"}
The tip callout with a custom title

```markdown
::: { .callout-tip title="Custom title"}
The tip callout with a custom title
:::
```
:::

::: { .callout-caution }
## Not the caution callout

```markdown
::: { .callout-caution }
## Not the caution callout
:::
```
:::

but customising the colour and icon of a callout is more difficult. The `quarto-custom-callout` extension allows us to make our own callouts.

## Defining a new callout

To make a new callout, add a new entry in `_quarto.yml` in the `custom-callout` block with the name of the callout. For instance, to add a new case study callout, we could use the code below:

```yaml
custom-callout:
  callout-case-study:
    title: "Case Study"
    icon-symbol: "🔍"
    color: "#FFA500"
```

and ensure that the `custom-callout` filter is called in `_quarto.yml`:

```yaml
filters:
  - custom-callout
```

::: { .callout-warning }
## Callout naming convention

We have chosen to give all of our callouts for this template the prefix `callout-` for continuity with the builtin callouts, and to aid with literate programming/self-documentation. Please keep to this convention when you define your own callouts.
:::

::: { .callout-tip }
Notice that the `icon-symbol` field accepts unicode icons and emojis.
:::

## Custom callouts in this template

We have defined the custom callouts below:

::: { .callout-case-study }
For describing case studies

```markdown
::: { .callout-case-study }
For describing case studies
:::
```
:::

::: { .callout-challenge }
For presenting a challenge to readers
```markdown
::: { .callout-challenge }
For presenting a challenge to readers
:::
```
:::

::: { .callout-data }
For describing datasets and data analysis
```markdown
::: { .callout-data }
For describing datasets and data analysis
:::
```
:::

::: { .callout-discussion }
For introducing discussion points
```markdown
::: { .callout-discussion }
For introducing discussion points
:::
```
:::

::: { .callout-microbe }
For summarising the properties of a microbe
```markdown
::: { .callout-microbe }
For summarising the properties of a microbe
:::
```
:::

::: { .callout-question }
For presenting a single question to readers
```markdown
::: { .callout-question }
For presenting a single question to readers
:::
```
:::

::: { .callout-questions }
For presenting multiple questions to readers
```markdown
::: { .callout-questions }
For presenting multiple questions to readers
:::
```
:::


::: { .callout-thumbs-up }
For general encouragement
```markdown
::: { .callout-thumbs-up }
For general encouragement
:::
```
:::

::: { .callout-todo }
For highlighting where we still need to do some work
```markdown
::: { .callout-todo }
For highlighting where we still need to do some work
:::
```
:::
